config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :clients do
  member do
    get "vote"
  end
end

  resources :jobs do
  member do
    get "vote"
  end
end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}

  root 'landings#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :client
  has_many :users
  has_and_belongs_to_many :users
  validates_formatting_of :jobzip, using: :us_zip
  acts_as_votable 
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy, :vote]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  #->Prelang (voting/acts_as_votable)
  def vote

    direction = params[:direction]

    # Make sure we've specified a direction
    raise "No direction parameter specified to #vote action." unless direction

    # Make sure the direction is valid
    unless ["like", "bad"].member? direction
      raise "Direction '#{direction}' is not a valid direction for vote method."
    end

    @job.vote_by voter: current_user, vote: direction

    redirect_to action: :index
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:client_id, :description, :jobstart, :jobend, :talenttype, :payrate, :jobzip, :jobaddress)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for @job, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :description, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :jobstart, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :jobstart, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :jobend, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :jobend, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :talenttype, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :talenttype, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :payrate, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :payrate, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :jobzip, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :jobzip, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :jobaddress, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :jobaddress, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  jobs_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Job %></h1>
</div>
<%= render :partial => 'form' %>

app/views/jobs/index.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => Job %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:jobstart) %></th>
      <th><%= model_class.human_attribute_name(:jobend) %></th>
      <th><%= model_class.human_attribute_name(:talenttype) %></th>
      <th><%= model_class.human_attribute_name(:payrate) %></th>
      <th><%= model_class.human_attribute_name(:jobzip) %></th>
      <th><%= model_class.human_attribute_name(:jobaddress) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.id %></td>
        <td><%= job.description %></td>
        <td><%= job.jobstart %></td>
        <td><%= job.jobend %></td>
        <td><%= job.talenttype %></td>
        <td><%= job.payrate %></td>
        <td><%= job.jobzip %></td>
        <td><%= job.jobaddress %></td>
        <td><%=l job.created_at, format: :long %></td>
        <td>
          <%= link_to job_path(job), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to job_path(job), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_job_path,
            :class => 'btn btn-primary' %>

app/views/jobs/new.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Job %></h1>
</div>
<%= render :partial => 'form' %>

app/views/jobs/show.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => Job %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @job.description %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:jobstart) %></dt>
      <dd><pre class="prettyprint"><%= @job.jobstart %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:jobend) %></dt>
      <dd><pre class="prettyprint"><%= @job.jobend %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:talenttype) %></dt>
      <dd><pre class="prettyprint"><%= @job.talenttype %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:payrate) %></dt>
      <dd><pre class="prettyprint"><%= @job.payrate %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:jobzip) %></dt>
      <dd><pre class="prettyprint"><%= @job.jobzip %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:jobaddress) %></dt>
      <dd><pre class="prettyprint"><%= @job.jobaddress %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              jobs_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_job_path(@job), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              job_path(@job),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>